name: hansol_high_school
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 기본 유틸
  path: ^1.8.3
  http: ^1.1.2
  intl: ^0.19.0
  url_launcher: ^6.2.1
  dio: ^5.4.0
  uuid: ^4.2.2
  io: ^1.0.4

  # 상태관리 / 서비스
  provider: ^6.1.1
  get_it: ^7.6.4

  # Firebase
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.3
  cloud_firestore: ^5.1.0

  # 알림 / 시간 / 로컬
  flutter_local_notifications: ^17.2.1+1
  android_alarm_manager_plus: ^4.0.7
  timezone: ^0.9.2
  shared_preferences: ^2.2.2
  flutter_timezone: ^3.0.1

  # 기기 정보 관련
  android_intent_plus: ^5.3.0
  package_info_plus: ^4.1.0
  device_info_plus: ^10.1.2
  connectivity_plus: ^4.0.2
  permission_handler: ^11.3.1

  # UI 관련
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  image_picker: ^1.0.5
  table_calendar: ^3.0.9
  path_provider: ^2.1.3
  screenshot: ^3.0.0
  share_plus: ^10.0.0
  universal_html: ^2.0.5
  numberpicker: ^2.1.2

  # 백그라운드 처리
#  workmanager: ^0.5.2-dev.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
