name: hansol_high_school
description: app for hansol high school students & teachers.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 기본 유틸
  path: ^1.8.3
  http: ^1.1.2
  intl: ^0.19.0
  uuid: ^4.2.2
  io: ^1.0.4

  # 상태관리 및 서비스
  provider: ^6.1.1
  get_it: ^8.0.3

  # Firebase
  firebase_core: ^3.3.0
  cloud_firestore: ^5.6.7
  firebase_messaging: ^15.0.3

  # 알림 / 로컬 저장 / 시간
  flutter_local_notifications: ^17.2.1+1
  shared_preferences: ^2.2.2
  timezone: ^0.9.2

  # UI / 기능
  cupertino_icons: ^1.0.6
  table_calendar: ^3.0.9
  path_provider: ^2.1.3
  screenshot: ^3.0.0
  share_plus: ^11.0.0
  numberpicker: ^2.1.2
  permission_handler: ^12.0.0+1
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
