// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArWvpbZ6mV2OpBA-hAdv-4vuSn1MsFbXA',
    appId: '1:74604661639:web:c22544644175aa7d99e122',
    messagingSenderId: '74604661639',
    projectId: 'hansol-high-school-326ab',
    authDomain: 'hansol-high-school-326ab.firebaseapp.com',
    databaseURL: 'https://hansol-high-school-326ab-default-rtdb.firebaseio.com',
    storageBucket: 'hansol-high-school-326ab.appspot.com',
    measurementId: 'G-J2W0RZQNP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJFGBf1AK7UtH39PPpAb1rWZXROnwVn1E',
    appId: '1:74604661639:android:546bbb7bcee1fc2899e122',
    messagingSenderId: '74604661639',
    projectId: 'hansol-high-school-326ab',
    databaseURL: 'https://hansol-high-school-326ab-default-rtdb.firebaseio.com',
    storageBucket: 'hansol-high-school-326ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgvdFLM6-5v1YqkMpvNt9z1-6uPmPd2mY',
    appId: '1:74604661639:ios:52832f92afb0ecbd99e122',
    messagingSenderId: '74604661639',
    projectId: 'hansol-high-school-326ab',
    databaseURL: 'https://hansol-high-school-326ab-default-rtdb.firebaseio.com',
    storageBucket: 'hansol-high-school-326ab.appspot.com',
    iosBundleId: 'com.example.hansolHighSchool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgvdFLM6-5v1YqkMpvNt9z1-6uPmPd2mY',
    appId: '1:74604661639:ios:ce985f25939e426b99e122',
    messagingSenderId: '74604661639',
    projectId: 'hansol-high-school-326ab',
    databaseURL: 'https://hansol-high-school-326ab-default-rtdb.firebaseio.com',
    storageBucket: 'hansol-high-school-326ab.appspot.com',
    iosBundleId: 'com.example.hansolHighSchool.RunnerTests',
  );
}
